### ISSUE TITLE
Lightbox bug when page is larger than window

### ISSUE THREAD

**Issue by drewmo** [abodelot/angular-lightbox#1]
If you have a page that has a height larger than the window size (as in you need to scroll down.) when the lightbox shows up you can keep scrolling down and see the edge of the dark area.

**Comment by abodelot** [comment]
Thanks for feedback, this should be easy to fix!

**Comment by abodelot** [comment]
Images taller than the window height are now resized, I think it's best for user experience so controls are still visible.
