### ISSUE TITLE
rendering issue during overlay when data is larger than screen height

### ISSUE THREAD

**Issue by Divine1** [abodelot/angular-lightbox#3]
1. View the bottom of the attached image. This is not a valid case. A valid case might be , during overlay, the image must be focused and browser scrollbar should be disabled.
2. if the image href is at the bottom of the page and there are text contents above image href and if the text contents occupy larger screen height,then onclick image href, the image appears on top of the page.The user has to scroll up to view the image. This is not a valid case. 

![image](https://cloud.githubusercontent.com/assets/10482177/21667691/225b6d74-d321-11e6-9473-5ccdc0133cf9.png)

**Comment by ecapistrang** [comment]
Modify the css file:

```
.angular-lightbox-overlay {

  position: fixed; /* change absolute to fixed */

  width: 100%;
  top: 0;
  bottom: 0;
  left: 0;
  z-index: 1000;
  background-color: rgba(0, 0, 0, .6);
  display: flex;
  align-items: center;
  justify-content: center;
}
```

**Comment by abodelot** [comment]
Thank you @ecapistrang for providing the fix.
